spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: testdbuser
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  flyway:
    locations: classpath:/db/migration
    enabled: true
    validate-on-migrate: true