server:
  servlet:
    context-path: /document-service

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: CO
    password: July2024
    properties:
      hibernate:
        format_sql: true
    show-sql: true